# Generated by Django 6.0 on 2025-12-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Đơn vị')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Trình độ học vấn')),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Cấp bậc')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Chức vụ')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Đội công tác')),
                ('leader', models.CharField(max_length=100, verbose_name='Đội trưởng')),
            ],
        ),
        migrations.CreateModel(
            name='theoretical_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Trình độ lý luận chính trị')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_num', models.CharField(max_length=10, unique=True, verbose_name='Số hiệu')),
                ('first_name', models.CharField(max_length=30, verbose_name='Họ')),
                ('last_name', models.CharField(max_length=30, verbose_name='Tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Giới tính')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Nơi sinh')),
                ('place_of_hometown', models.CharField(max_length=100, verbose_name='Quê quán')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_in_group', models.DateField(verbose_name='Ngày vào đoàn')),
                ('is_member', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='', max_length=1, verbose_name='Đảng viên')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Ảnh')),
                ('indentity_card_number', models.CharField(max_length=20, unique=True, verbose_name='Số CMND/CCCD')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Đơn vị')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.education', verbose_name='Trình độ học vấn')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.level', verbose_name='Cấp bậc')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức vụ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.team', verbose_name='Đội công tác')),
                ('theoretical_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.theoretical_level', verbose_name='Trình độ lý luận chính trị')),
            ],
        ),
    ]
