# Generated by Django 6.0 on 2026-01-30 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Đơn vị')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Trình độ học vấn')),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Cấp bậc')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Chức vụ')),
            ],
        ),
        migrations.CreateModel(
            name='theoretical_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Trình độ lý luận chính trị')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_num', models.CharField(max_length=10, unique=True, verbose_name='Số hiệu')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('current_name', models.CharField(max_length=100, verbose_name='Tên hiện tại')),
                ('day_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, verbose_name='Giới tính')),
                ('place_of_hometown', models.CharField(max_length=100, verbose_name='Quê quán')),
                ('current_residence', models.CharField(max_length=100, verbose_name='Nơi cư trú hiện tại')),
                ('nation', models.CharField(max_length=50, verbose_name='Dân tộc')),
                ('religion', models.CharField(max_length=50, verbose_name='Tôn giáo')),
                ('family_job', models.CharField(max_length=100, verbose_name='Nghề nghiệp của gia đình')),
                ('before_job', models.CharField(max_length=100, verbose_name='Công việc trước đây')),
                ('date_in_group', models.DateField(verbose_name='Ngày vào đoàn')),
                ('union', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], max_length=1, verbose_name='Đoàn viên')),
                ('day_of_joining_the_party', models.DateField(verbose_name='Ngày vào Đảng')),
                ('day_offical', models.DateField(verbose_name='Ngày chính thức')),
                ('recruitment_day', models.DateField(verbose_name='Ngày tuyển dụng')),
                ('date_of_joining_the_police', models.DateField(verbose_name='Ngày vào công an')),
                ('recruitment_source', models.CharField(max_length=100, verbose_name='Nguồn tuyển dụng')),
                ('blood_type', models.CharField(max_length=10, verbose_name='Nhóm máu')),
                ('appellation', models.CharField(max_length=50, verbose_name='Danh hiệu được phong')),
                ('keep_records', models.CharField(max_length=100, verbose_name='Địa chỉ hồ sơ')),
                ('forte_ability', models.CharField(max_length=100, verbose_name='Năng lực nổi bật')),
                ('Descriptions', models.TextField(null=True, verbose_name='Mô tả')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee_avatars/', verbose_name='Ảnh chân dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('recruitment_place', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Nơi tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_history', models.TextField(verbose_name='Đặc điểm lịch sử')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Health',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_check', models.DateField(verbose_name='Ngày kiểm tra sức khỏe')),
                ('heal_check', models.CharField(max_length=100, verbose_name='Tình trạng sức khỏe')),
                ('wounded_soldiers', models.CharField(max_length=100, verbose_name='Thương binh')),
                ('agency', models.CharField(max_length=100, verbose_name='Đơn vị khám bệnh')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Foreign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Đến ngày')),
                ('nation', models.CharField(max_length=100, verbose_name='Quốc gia')),
                ('reason', models.TextField(verbose_name='Lý do đến')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Disengaged',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField(verbose_name='Ngày thôi việc')),
                ('reason', models.CharField(max_length=100, verbose_name='Lý do')),
                ('address', models.CharField(max_length=100, verbose_name='Nơi chuyển đến')),
                ('decision', models.CharField(max_length=100, verbose_name='Số quyết định')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_party', models.CharField(max_length=100, verbose_name='Kỷ luật Đảng')),
                ('date_issue_party', models.DateField(verbose_name='Ngày kỷ luật Đảng')),
                ('discipline_government', models.CharField(max_length=100, verbose_name='Kỷ luật chính quyền')),
                ('date_issue_government', models.DateField(verbose_name='Ngày kỷ luật chính quyền')),
                ('violations', models.CharField(max_length=100, verbose_name='Vi phạm')),
                ('summary_of_violations', models.TextField(verbose_name='Tóm tắt vi phạm')),
                ('date_recognizes_progress', models.DateField(verbose_name='Ngày nhận tiến bộ')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_issue', models.DateField(verbose_name='Ngày nhận khen thưởng')),
                ('forms_of_reward', models.CharField(max_length=100, verbose_name='Hình thức khen thưởng')),
                ('award_level', models.CharField(max_length=100, verbose_name='Cấp khen thưởng')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Army',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_join', models.DateField(verbose_name='Ngày nhập ngũ')),
                ('level', models.CharField(max_length=50, verbose_name='Bậc hàm')),
                ('position', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('place', models.CharField(max_length=100, verbose_name='Nơi làm việc')),
                ('date_out', models.DateField(verbose_name='Ngày xuất ngũ')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_PartyCommittee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_committee', models.CharField(max_length=100, unique=True, verbose_name='Đảng ủy')),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Đến ngày')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100, verbose_name='Loại quan hệ')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên thân nhân')),
                ('date_of_birth', models.DateField(verbose_name='Năm sinh')),
                ('career', models.CharField(max_length=100, verbose_name='Nghề nghiệp')),
                ('title', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('work_unit', models.CharField(max_length=100, verbose_name='Nơi làm việc')),
                ('address', models.CharField(max_length=100, verbose_name='Địa chỉ')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_ResultWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, verbose_name='Năm')),
                ('result', models.CharField(max_length=100, verbose_name='Kết quả công tác')),
                ('comments', models.TextField(null=True, verbose_name='Nhận xét đánh giá')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_SalaryProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50, verbose_name='Cấp bậc')),
                ('date_issue', models.DateField(verbose_name='Ngày nhận cấp bậc')),
                ('salary_coefficient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hệ số lương')),
                ('date_receive', models.DateField(verbose_name='Ngày nhận hệ số lương')),
                ('decision_date', models.DateField(verbose_name='Ngày quyết định')),
                ('decision_number', models.CharField(max_length=100, verbose_name='Số quyết định')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Đến ngày')),
                ('specialized', models.CharField(max_length=100, verbose_name='Chuyên môn')),
                ('formality', models.CharField(max_length=100, verbose_name='Hình thức đào tạo')),
                ('level', models.CharField(max_length=100, verbose_name='Trình độ')),
                ('training_school', models.CharField(max_length=100, verbose_name='Trường đào tạo')),
                ('equal_number', models.CharField(max_length=100, verbose_name='Số bằng')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_WithForeigners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100, verbose_name='Quan hệ')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên thân nhân')),
                ('date_of_birth', models.DateField(verbose_name='Năm sinh')),
                ('job', models.CharField(max_length=100, verbose_name='Nghề nghiệp')),
                ('address', models.CharField(max_length=100, verbose_name='Địa chỉ')),
                ('nation', models.CharField(max_length=100, verbose_name='Hiện ở Quốc gia')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phụ cấp')),
                ('date_of_receipt', models.DateField(verbose_name='Ngày nhận chức danh')),
                ('form_of_appointment', models.CharField(max_length=100, verbose_name='Hình thức bổ nhiệm')),
                ('decision_number', models.CharField(max_length=100, verbose_name='Số quyết định')),
                ('decision_date', models.DateField(verbose_name='Ngày quyết định')),
                ('stop_decision_date', models.DateField(blank=True, null=True, verbose_name='Ngày dừng quyết định')),
                ('is_active', models.CharField(max_length=1, null=True, verbose_name='Hiệu lực')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_titles/', verbose_name='File đính kèm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateTimeField(verbose_name='Ngày sửa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_titles_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('emp', models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_titles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
                ('emp_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức danh')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_position', models.DateField(verbose_name='Ngày quy hoạch')),
                ('votes', models.CharField(max_length=100, verbose_name='Số phiếu bầu')),
                ('date_stop_position', models.DateField(verbose_name='Ngày dừng quy hoạch')),
                ('reason_stop_position', models.CharField(max_length=100, verbose_name='Lý do dừng quy hoạch')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
                ('position', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức vụ')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Đội công tác')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Đơn vị')),
            ],
        ),
        migrations.CreateModel(
            name='usercompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
