# Generated by Django 6.0 on 2026-02-06 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_position',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Position_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_position',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_Position/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_position',
            name='is_active',
            field=models.CharField(max_length=1, null=True, verbose_name='Hiệu lực'),
        ),
        migrations.AddField(
            model_name='emp_position',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_position',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Position_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AlterField(
            model_name='emp_position',
            name='date_stop_position',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dừng quy hoạch'),
        ),
        migrations.AlterField(
            model_name='emp_position',
            name='reason_stop_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lý do dừng quy hoạch'),
        ),
        migrations.AlterField(
            model_name='emp_title',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
    ]
