# Generated by Django 6.0 on 2025-12-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Đơn vị'),
        ),
    ]
