# Generated by Django 6.0 on 2026-02-07 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_emp_position_created_at_emp_position_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_partycommittee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_partycommittee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_PartyCommittee_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_partycommittee',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_PartyCommittee/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_partycommittee',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_partycommittee',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_PartyCommittee_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
    ]
