# Generated by Django 6.0 on 2026-02-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_emp_partycommittee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Đảng ủy')),
            ],
        ),
        migrations.AlterField(
            model_name='emp_partycommittee',
            name='party_committee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.committee', verbose_name='Cấp ủy Đảng'),
        ),
    ]
