# Generated by Django 6.0 on 2025-12-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_team_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
    ]
