# Generated by Django 6.0 on 2026-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_emp_position_created_at_emp_position_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_position',
            name='date_stop_position',
            field=models.DateField(null=True, verbose_name='Ngày dừng quy hoạch'),
        ),
    ]
