# Generated by Django 6.0 on 2026-02-10 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_committee_alter_emp_partycommittee_party_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_training',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Training_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_training',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_Training/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_training',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_training',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Training_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
    ]
