# Generated by Django 6.0 on 2026-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_emp_position_date_stop_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_position',
            name='date_stop_position',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dừng quy hoạch'),
        ),
    ]
