# Generated by Django 6.0 on 2026-02-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_emp_training_created_at_emp_training_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='formality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hình thức đào tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Traning_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cấp đào tạo')),
            ],
        ),
        migrations.AlterField(
            model_name='emp_training',
            name='formality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.formality', verbose_name='Hình thức đào tạo'),
        ),
        migrations.AlterField(
            model_name='emp_training',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.traning_level', verbose_name='Trình độ'),
        ),
    ]
