# Generated by Django 6.0 on 2026-02-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_formality_traning_level_alter_emp_training_formality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_training',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Đến ngày'),
        ),
    ]
