# Generated by Django 6.0 on 2026-01-14 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_emp_information_emp_history_emp_health_emp_foreign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_title',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_title',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_titles/', verbose_name='File đính kèm'),
        ),
        migrations.AlterField(
            model_name='emp_information',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='emp_information',
            name='recruitment_place',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Nơi tuyển dụng'),
        ),
    ]
