# Generated by Django 6.0 on 2026-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_emp_title_created_at_emp_title_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_title',
            name='emp_title',
            field=models.CharField(max_length=100, verbose_name='Chức danh'),
        ),
    ]
