# Generated by Django 6.0 on 2026-02-23 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_emp_training_to_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_workProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
                ('work', models.CharField(max_length=100, verbose_name='Công tác chuyên môn')),
                ('decision_number', models.CharField(max_length=100, verbose_name='Số quyết định')),
                ('decision_date', models.DateField(verbose_name='Ngày quyết định')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_workProcess/', verbose_name='File đính kèm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_workProcess_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('emp', models.ForeignKey(db_column='emp_num', default='', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên')),
                ('emp_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Đơn vị công tác')),
                ('emp_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức danh đảm nhiệm')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_workProcess_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
            ],
        ),
    ]
