# Generated by Django 6.0 on 2026-02-25 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_emp_workprocess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_salaryprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_salaryprocess',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_SalaryProcess_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_salaryprocess',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_SalaryProcess/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_salaryprocess',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_salaryprocess',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_SalaryProcess_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AlterField(
            model_name='emp_salaryprocess',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.level', verbose_name='Cấp bậc'),
        ),
    ]
