# Generated by Django 6.0 on 2026-01-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_emp_title_emp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_title',
            name='emp_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức danh'),
        ),
    ]
