# Generated by Django 6.0 on 2026-02-25 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_emp_salaryprocess_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='award_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cấp khen thưởng')),
            ],
        ),
        migrations.CreateModel(
            name='award_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hình thức khen thưởng')),
            ],
        ),
        migrations.RemoveField(
            model_name='emp_awards',
            name='forms_of_reward',
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Awards_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_Awards/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Awards_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AlterField(
            model_name='emp_awards',
            name='award_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.award_level', verbose_name='Cấp khen thưởng'),
        ),
        migrations.AddField(
            model_name='emp_awards',
            name='reward_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.award_type', verbose_name='Hình thức khen thưởng'),
        ),
    ]
