# Generated by Django 6.0 on 2026-01-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_emp_title_emp_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_title',
            name='is_active',
            field=models.CharField(max_length=1, null=True, verbose_name='Hiệu lực'),
        ),
        migrations.AlterField(
            model_name='emp_title',
            name='stop_decision_date',
            field=models.DateField(null=True, verbose_name='Ngày dừng quyết định'),
        ),
    ]
