# Generated by Django 6.0 on 2026-01-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_emp_title_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_title',
            name='emp',
            field=models.ForeignKey(db_column='emp_num', on_delete=django.db.models.deletion.CASCADE, to='employee.emp_information', to_field='emp_num', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='emp_title',
            name='emp_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Chức danh'),
        ),
    ]
