# Generated by Django 6.0 on 2026-02-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_award_level_award_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_awards',
            old_name='reward_type',
            new_name='award_type',
        ),
    ]
