# Generated by Django 6.0 on 2026-02-26 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_reward_type_emp_awards_award_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_discipline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Discipline_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_discipline',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_Discipline/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_discipline',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_discipline',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Discipline_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='date_issue_government',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kỷ luật chính quyền'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='date_issue_party',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kỷ luật Đảng'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='date_recognizes_progress',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nhận tiến bộ'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='discipline_government',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kỷ luật chính quyền'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='discipline_party',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kỷ luật Đảng'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='summary_of_violations',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt vi phạm'),
        ),
        migrations.AlterField(
            model_name='emp_discipline',
            name='violations',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vi phạm'),
        ),
    ]
