# Generated by Django 6.0 on 2026-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_emp_title_emp_alter_emp_title_emp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_title',
            name='stop_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dừng quyết định'),
        ),
    ]
