# Generated by Django 6.0 on 2026-02-26 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_emp_discipline_created_at_emp_discipline_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Quan hệ gia đình')),
            ],
        ),
        migrations.AddField(
            model_name='emp_relationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_relationship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Relationship_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='emp_relationship',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_Relationship/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='emp_relationship',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AddField(
            model_name='emp_relationship',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_Relationship_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên thân nhân'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='work_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi làm việc'),
        ),
        migrations.AlterField(
            model_name='emp_relationship',
            name='relationship_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.relationship_type', verbose_name='Loại quan hệ'),
        ),
    ]
