# Generated by Django 6.0 on 2026-03-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_emp_health_created_at_emp_health_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_health',
            name='agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.company', verbose_name='Cơ quan khám sức khỏe'),
        ),
        migrations.AlterField(
            model_name='emp_health',
            name='wounded_soldiers',
            field=models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], max_length=1, verbose_name='Thương binh'),
        ),
    ]
